Traceback (most recent call last):
  File "./tracebackEx.py", line 6, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
